# General GitHub Repository Settings
repository:
  license: MIT      # Select a license from the options below

# MATLAB Toolbox Settings
matlab_toolbox:
  namespace_name: AIDIF                         # A unique namespace for your toolbox
  toolbox_name: AIDIF Matlab Toolbox            # Name of the MATLAB toolbox                  
  author_name: Lane Desborough                     
  author_email: lane@aidif.org         
  author_company: aidif.org                     # Author's company or organization
  toolbox_summary: Credible Set of Models to perform pre-clinical evaluation of AID systems and their components.
  toolbox_description: |
    A comprehensive set of validated models and tools to perform pre-clincial evaluation for AID systems and components 
     - physiological models
     - disturbance and noise models
     - parameter distributions
     - sensitivity analysis
     - credibility frameworks
     - outcome measures and performance metrics
     - summary reports
     - simulink components
  dependencies:                                     # Required MATLAB products
    - MATLAB
    - Matlab Simulink

# Publishing options
codecov:
  badge_token: null

fileexchange:
  fex_url: null
